name: app_navtour
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  split_view: ^3.2.1
  flutter_map: ^3.1.0
  latlong2: ^0.8.1 
  location: ^5.0.3
  geolocator: ^10.1.0
  http:
  provider: ^6.0.5
  gallery_saver: ^2.3.2
  image_picker: ^1.0.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
